export const allowedLocations = ['europe', 'asia', 'africa', 'south_america', 'north_america'];

export const allowedStudyFields = [
  'it',
  'construction_and_infrastructure',
  'geotechnics',
  'machine_and_process_engineering',
  'clean_energy',
  'water_and_sanitation',
];

export const plastics = ['pet', 'hdpe', 'pvc', 'ldpe', 'pp', 'ps', 'other']

export const countries = ['afghanistan','albania', 'algeria', 'andorra', 'angola', 'antigua_and_barbuda', 'argentina', 'armenia', 'australia',
  'austria', 'azerbaijan', 'bahamas', 'bahrain', 'bangladesh', 'barbados', 'belarus', 'belgium', 'belize', 'benin', 'bhutan',
  'bolivia', 'bosnia_and_herzegovina', 'botswana', 'brazil', 'brunei', 'bulgaria', 'burkina_faso', 'burundi', 'cabo_verde', 'cambodia',
  'cameroon', 'canada', 'central_african_republic', 'chad', 'chile', 'china', 'colombia', 'comoros', 'congo_brazzaville', 'congo_kinshasa',
  'costa_rica', 'croatia', 'cuba', 'cyprus', 'czech_republic', 'denmark', 'djibouti', 'dominica', 'dominican_republic', 'east_timor',
  'ecuador', 'egypt', 'el_salvador', 'equatorial_guinea', 'eritrea', 'estonia', 'eswatini', 'ethiopia', 'fiji', 'finland', 'france',
  'gabon', 'gambia', 'georgia', 'germany', 'ghana', 'greece', 'grenada', 'guatemala', 'guinea', 'guinea_bissau', 'guyana', 'haiti',
  'honduras', 'hungary', 'iceland', 'india', 'indonesia', 'iran', 'iraq', 'ireland', 'israel', 'italy', 'ivory_coast', 'jamaica', 'japan',
  'jordan', 'kazakhstan', 'kenya', 'kiribati', 'kosovo', 'kuwait', 'kyrgyzstan', 'laos', 'latvia', 'lebanon', 'lesotho', 'liberia',
  'libya', 'liechtenstein', 'lithuania', 'luxembourg', 'madagascar', 'malawi', 'malaysia', 'maldives', 'mali', 'malta', 'marshall_islands',
  'mauritania', 'mauritius', 'mexico', 'micronesia', 'moldova', 'monaco', 'mongolia', 'montenegro', 'morocco', 'mozambique', 'myanmar',
  'namibia', 'nauru', 'nepal', 'netherlands', 'new_zealand', 'nicaragua', 'niger', 'nigeria', 'north_korea', 'north_macedonia', 'norway',
  'oman', 'pakistan', 'palau', 'panama', 'papua_new_guinea', 'paraguay', 'peru', 'philippines', 'poland', 'portugal', 'qatar', 'romania',
  'russia', 'rwanda', 'saint_kitts_and_nevis', 'saint_lucia', 'saint_vincent_and_the_grenadines', 'samoa', 'san_marino', 'sao_tome_and_principe',
  'saudi_arabia', 'senegal', 'serbia', 'seychelles', 'sierra_leone', 'singapore', 'slovakia', 'slovenia', 'solomon_islands', 'somalia',
  'south_africa', 'south_korea', 'south_sudan', 'spain', 'sri_lanka', 'sudan', 'suriname', 'sweden', 'switzerland', 'syria', 'taiwan',
  'tajikistan', 'tanzania', 'thailand', 'togo', 'tonga', 'trinidad_and_tobago', 'tunisia', 'turkey', 'turkmenistan', 'tuvalu', 'uganda',
  'ukraine', 'united_arab_emirates', 'united_kingdom', 'united_states', 'uruguay', 'uzbekistan', 'vanuatu', 'vatican_city', 'venezuela',
  'vietnam', 'yemen', 'zambia', 'zimbabwe'
];

export enum studyFields {
  study_field = 'Study field',
  it = 'IT',
  construction_and_infrastructure = 'Construction and infrastructure',
  geotechnics = 'Geotechnics',
  machine_and_process_engineering = 'Machine and process engineering',
  clean_energy = 'Clean energy',
  water_and_sanitation = 'Water and sanitation',
}

export enum locations {
  location = 'Location',
  europe = 'Europe',
  asia = 'Asia',
  africa = 'Africa',
  south_america = 'South America',
  north_america = 'North America',
}

export enum sortByEnum {
  deadline = 'Deadline',
  duration = 'Duration',
  title = 'Title',
}

export enum plastic {pet= 'PET', hdpe= 'HDPE', pvc= 'PVC', ldpe= 'LDPE', pp= 'PP', ps= 'PS', other= 'Other'}

export enum country {
  country = 'Country',
  afghanistan = 'Afghanistan',
  albania = 'Albania',
  algeria = 'Algeria',
  andorra = 'Andorra',
  angola = 'Angola',
  antigua_and_barbuda = 'Antigua and Barbuda',
  argentina = 'Argentina',
  armenia = 'Armenia',
  australia = 'Australia',
  austria = 'Austria',
  azerbaijan = 'Azerbaijan',
  bahamas = 'Bahamas',
  bahrain = 'Bahrain',
  bangladesh = 'Bangladesh',
  barbados = 'Barbados',
  belarus = 'Belarus',
  belgium = 'Belgium',
  belize = 'Belize',
  benin = 'Benin',
  bhutan = 'Bhutan',
  bolivia = 'Bolivia',
  bosnia_and_herzegovina = 'Bosnia and Herzegovina',
  botswana = 'Botswana',
  brazil = 'Brazil',
  brunei = 'Brunei',
  bulgaria = 'Bulgaria',
  burkina_faso = 'Burkina Faso',
  burundi = 'Burundi',
  cabo_verde = 'Cabo Verde',
  cambodia = 'Cambodia',
  cameroon = 'Cameroon',
  canada = 'Canada',
  central_african_republic = 'Central African Republic',
  chad = 'Chad',
  chile = 'Chile',
  china = 'China',
  colombia = 'Colombia',
  comoros = 'Comoros',
  congo_brazzaville = 'Congo (Brazzaville)',
  congo_kinshasa = 'Congo (Kinshasa)',
  costa_rica = 'Costa Rica',
  croatia = 'Croatia',
  cuba = 'Cuba',
  cyprus = 'Cyprus',
  czech_republic = 'Czech Republic',
  denmark = 'Denmark',
  djibouti = 'Djibouti',
  dominica = 'Dominica',
  dominican_republic = 'Dominican Republic',
  east_timor = 'East Timor',
  ecuador = 'Ecuador',
  egypt = 'Egypt',
  el_salvador = 'El Salvador',
  equatorial_guinea = 'Equatorial Guinea',
  eritrea = 'Eritrea',
  estonia = 'Estonia',
  eswatini = 'Eswatini',
  ethiopia = 'Ethiopia',
  fiji = 'Fiji',
  finland = 'Finland',
  france = 'France',
  gabon = 'Gabon',
  gambia = 'Gambia',
  georgia = 'Georgia',
  germany = 'Germany',
  ghana = 'Ghana',
  greece = 'Greece',
  grenada = 'Grenada',
  guatemala = 'Guatemala',
  guinea = 'Guinea',
  guinea_bissau = 'Guinea-Bissau',
  guyana = 'Guyana',
  haiti = 'Haiti',
  honduras = 'Honduras',
  hungary = 'Hungary',
  iceland = 'Iceland',
  india = 'India',
  indonesia = 'Indonesia',
  iran = 'Iran',
  iraq = 'Iraq',
  ireland = 'Ireland',
  israel = 'Israel',
  italy = 'Italy',
  ivory_coast = 'Ivory Coast',
  jamaica = 'Jamaica',
  japan = 'Japan',
  jordan = 'Jordan',
  kazakhstan = 'Kazakhstan',
  kenya = 'Kenya',
  kiribati = 'Kiribati',
  kosovo = 'Kosovo',
  kuwait = 'Kuwait',
  kyrgyzstan = 'Kyrgyzstan',
  laos = 'Laos',
  latvia = 'Latvia',
  lebanon = 'Lebanon',
  lesotho = 'Lesotho',
  liberia = 'Liberia',
  libya = 'Libya',
  liechtenstein = 'Liechtenstein',
  lithuania = 'Lithuania',
  luxembourg = 'Luxembourg',
  madagascar = 'Madagascar',
  malawi = 'Malawi',
  malaysia = 'Malaysia',
  maldives = 'Maldives',
  mali = 'Mali',
  malta = 'Malta',
  marshall_islands = 'Marshall Islands',
  mauritania = 'Mauritania',
  mauritius = 'Mauritius',
  mexico = 'Mexico',
  micronesia = 'Micronesia',
  moldova = 'Moldova',
  monaco = 'Monaco',
  mongolia = 'Mongolia',
  montenegro = 'Montenegro',
  morocco = 'Morocco',
  mozambique = 'Mozambique',
  myanmar = 'Myanmar',
  namibia = 'Namibia',
  nauru = 'Nauru',
  nepal = 'Nepal',
  netherlands = 'Netherlands',
  new_zealand = 'New Zealand',
  nicaragua = 'Nicaragua',
  niger = 'Niger',
  nigeria = 'Nigeria',
  north_korea = 'North Korea',
  north_macedonia = 'North Macedonia',
  norway = 'Norway',
  oman = 'Oman',
  pakistan = 'Pakistan',
  palau = 'Palau',
  panama = 'Panama',
  papua_new_guinea = 'Papua New Guinea',
  paraguay = 'Paraguay',
  peru = 'Peru',
  philippines = 'Philippines',
  poland = 'Poland',
  portugal = 'Portugal',
  qatar = 'Qatar',
  romania = 'Romania',
  russia = 'Russia',
  rwanda = 'Rwanda',
  saint_kitts_and_nevis = 'Saint Kitts and Nevis',
  saint_lucia = 'Saint Lucia',
  saint_vincent_and_the_grenadines = 'Saint Vincent and the Grenadines',
  samoa = 'Samoa',
  san_marino = 'San Marino',
  sao_tome_and_principe = 'Sao Tome and Principe',
  saudi_arabia = 'Saudi Arabia',
  senegal = 'Senegal',
  serbia = 'Serbia',
  seychelles = 'Seychelles',
  sierra_leone = 'Sierra Leone',
  singapore = 'Singapore',
  slovakia = 'Slovakia',
  slovenia = 'Slovenia',
  solomon_islands = 'Solomon Islands',
  somalia = 'Somalia',
  south_africa = 'South Africa',
  south_korea = 'South Korea',
  south_sudan = 'South Sudan',
  spain = 'Spain',
  sri_lanka = 'Sri Lanka',
  sudan = 'Sudan',
  suriname = 'Suriname',
  sweden = 'Sweden',
  switzerland = 'Switzerland',
  syria = 'Syria',
  taiwan = 'Taiwan',
  tajikistan = 'Tajikistan',
  tanzania = 'Tanzania',
  thailand = 'Thailand',
  togo = 'Togo',
  tonga = 'Tonga',
  trinidad_and_tobago = 'Trinidad and Tobago',
  tunisia = 'Tunisia',
  turkey = 'Turkey',
  turkmenistan = 'Turkmenistan',
  tuvalu = 'Tuvalu',
  uganda = 'Uganda',
  ukraine = 'Ukraine',
  united_arab_emirates = 'United Arab Emirates',
  united_kingdom = 'United Kingdom',
  united_states = 'United States',
  uruguay = 'Uruguay',
  uzbekistan = 'Uzbekistan',
  vanuatu = 'Vanuatu',
  vatican_city = 'Vatican City',
  venezuela = 'Venezuela',
  vietnam = 'Vietnam',
  yemen = 'Yemen',
  zambia = 'Zambia',
  zimbabwe = 'Zimbabwe'
}